// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIz1QgtwaBDM8ptf4LgNqxYr0L4RSWLys',
    appId: '1:172786292841:web:65d0fac82a8fc382aaeaf8',
    messagingSenderId: '172786292841',
    projectId: 'recipe-ai-175b2',
    authDomain: 'recipe-ai-175b2.firebaseapp.com',
    storageBucket: 'recipe-ai-175b2.firebasestorage.app',
    measurementId: 'G-0EJ2E93VM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS8cBB1GELpPeTWA9_cSGtkOwQE3zgbmE',
    appId: '1:172786292841:android:4f3b5c9fd7f41e8aaaeaf8',
    messagingSenderId: '172786292841',
    projectId: 'recipe-ai-175b2',
    storageBucket: 'recipe-ai-175b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2z3RJSo67kptoCil8Y_0LBZY1SUeybfo',
    appId: '1:172786292841:ios:f8395102e542ffe3aaeaf8',
    messagingSenderId: '172786292841',
    projectId: 'recipe-ai-175b2',
    storageBucket: 'recipe-ai-175b2.firebasestorage.app',
    iosClientId: '172786292841-m5ufi5o8q9ststfpq57erl2bhf1gghib.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeAi',
  );

}