name: class_2025_b
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.4.10
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_storage:
  google_sign_in: ^6.2.1
  google_generative_ai: ^0.3.2
  cloud_firestore: ^4.13.0
  cloud_functions: 
  sqflite: ^2.3.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  
  build_runner: ^2.4.9
  riverpod_generator: ^2.3.11


flutter:
  uses-material-design: true
